Update createpr.yml

diff --git a/.github/workflows/createpr.yml b/.github/workflows/createpr.yml
--- a/.github/workflows/createpr.yml
+++ b/.github/workflows/createpr.yml
@@ -6,7 +6,7 @@ on:
       - staging
 
 jobs:
-  test_frontend:
+  test_and_build_frontend:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
@@ -32,20 +32,20 @@ jobs:
             npm install --legacy-peer-deps
           fi
 
-      - name: Run linter
+      - name: Display available scripts
         working-directory: ./
-        run: npm run lint || echo "Linting failed but continuing"
+        run: npm run
 
       - name: Run tests
         working-directory: ./
-        run: npm test || echo "Tests failed but continuing"
+        run: npm test -- --watchAll=false || echo "Tests failed but continuing"
 
       - name: Build project
         working-directory: ./
         run: npm run build || echo "Build failed but continuing"
 
   create_pull_request:
-    needs: test_frontend
+    needs: test_and_build_frontend
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
